version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: hydroflow-api:latest
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY
      - HYDROFLOW_ENVIRONMENT=production
    restart: unless-stopped
